# Generated by Django 3.1.7 on 2021-03-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.shift'),
        ),
    ]
