# Generated by Django 3.1.7 on 2021-04-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20210323_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='daily_id',
        ),
        migrations.RemoveField(
            model_name='extrastop',
            name='daily_id',
        ),
    ]
