# Generated by Django 3.1.7 on 2021-04-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20210414_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='daily_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extrastop',
            name='daily_id',
            field=models.IntegerField(default=0),
        ),
    ]
