# Generated by Django 3.1.7 on 2021-04-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20210414_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='daily_delivery_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='daily_extra_stop_id',
            field=models.IntegerField(default=0),
        ),
    ]
