# Generated by Django 3.1.7 on 2021-04-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20210414_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='card',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='cash',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='unknown',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
