# Generated by Django 3.2.3 on 2021-06-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0009_auto_20210604_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrastop',
            name='daily_id',
            field=models.IntegerField(default=0),
        ),
    ]
