# Generated by Django 3.2.3 on 2021-06-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_extrastop_daily_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='daily_extra_stop_id',
            field=models.IntegerField(default=0),
        ),
    ]
